name: Docker Build (Hub)

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - dev
    tags:
      - 'v*'

jobs:
  Build-Alpine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            no767/rin-commands-api
          tags: |
            type=semver,pattern={{version}},suffix=-alpine
            type=semver,pattern={{major}}.{{minor}},suffix=-alpine
            type=semver,pattern={{major}},suffix=-alpine
            type=edge,branch=dev,suffix=-alpine

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3.3.3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-hub-alpine-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-hub-alpine-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Alpine-Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new-hub-alpine

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-hub-alpine /tmp/.buildx-cache

  Build-Debian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            no767/rin-commands-api
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern={{version}},suffix=-debian
            type=semver,pattern={{major}}.{{minor}},suffix=-debian
            type=semver,pattern={{major}},suffix=-debian
            type=edge,branch=dev,suffix=-debian

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3.3.3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-hub-debian-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-hub-debian-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Debian-Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new-hub-debian

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-hub-debian /tmp/.buildx-cache