name: Docker Build (Docker Hub)

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - master
      - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image: [alpine, debian]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            no767/rin-commands-api
          tags: |
            type=semver,pattern={{raw}}
            type=edge,branch=dev,suffix=${{ matrix.base-image }}

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3.0.8
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./${{ matrix.base-image }}-Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache